### ISSUE TITLE
aks create issue Lab8

### ISSUE THREAD

**Issue by vdesc** [FrenchBarbusCorp/Workshop-Azure-Kubernetes-Service-2days#16]
<img width="926" alt="2023-01-05 10_52_47-vincent@FR-5CG00260Y8_ ~_Workshop-Azure-Kubernetes-Service-2days_Lab_7" src="https://user-images.githubusercontent.com/67049906/210752965-b905d8e7-2095-4e0d-87a5-03afe0321915.png">

**Comment by squasta** [comment]
Normalement cette option n'est pas nécessaire mais comme ça ne coûte rien, je vais la rajouter au lab
