### ISSUE TITLE
Typo Lab_5

### ISSUE THREAD

**Issue by samok** [FrenchBarbusCorp/Workshop-Azure-Kubernetes-Service-2days#17]
Créez un fichier "acr-nginx.yml" (ex: touch acr-ngnix.yml)
->
Créez un fichier "acr-nginx.yml" (ex: touch acr-nginx.yml)

l'exemple touch contient un nom de fichier acr-ngnix.yml, qui sera incohérent avec le reste des commandes appelés référençant le fichier.

**Comment by squasta** [comment]
Corrigé. Merci :)
